### ISSUE TITLE
multiple inheritance inconsistently highlighted

### ISSUE THREAD

**Issue by luclu** [Latrasis/linter-solidity#1]
see https://github.com/caktux/language-ethereum/issues/7
<img width="392" alt="unbenannt-1" src="https://cloud.githubusercontent.com/assets/10135872/15960927/7013ed8e-2f02-11e6-9a7b-3cbd807a2d6f.png">

**Comment by Latrasis** [comment]
@luclu: Thank you for noticing! I'm not overly familiar with the grammar highlighting defitions: http://docs.sublimetext.info/en/latest/reference/syntaxdefs.html?highlight=syntax but i'll see what I can do. I used @caktux grammar definitions from language-solidity.

**Comment by caktux** [comment]
Fixed in caktux/language-ethereum@ea957e9, feel free to grab the updated grammar file :)

**Comment by Latrasis** [comment]
@caktux Awesome! Thank you!

**Comment by Latrasis** [comment]
https://github.com/Latrasis/linter-solidity/commit/042071aa0f3cdb22a370d7a29d32c49d2cd09af0
