### ISSUE TITLE
help me decide what I should use instead of throw (link to docs)

### ISSUE THREAD

**Issue by ghost** [Latrasis/linter-solidity#14]
![help me decide which i should use link me to the docs](https://user-images.githubusercontent.com/8081877/28164622-1eccec00-67c8-11e7-819f-2c1955496599.png)

**Comment by ghost** [comment]
http://solidity.readthedocs.io/en/develop/control-structures.html?highlight=throw%20require#error-handling-assert-require-revert-and-exceptions

**Comment by adibas03** [comment]
So, as described by the documentation, the functions are best in different scenarios.  
`require`: perform checks on inputs into the function, or external variables
`assert`: perform checks on internal values or variables in the function
`revert`: is an alias for throw, the original call to cancel transaction and revert all state changes.

Hope this helps

**Comment by ghost** [comment]
Sorry, I mean I think the message should link to the documentation, or give the information you have in your comment.
