### ISSUE TITLE
File not found Error when importing from truffle

### ISSUE THREAD

**Issue by buck-ross** [Latrasis/linter-solidity#22]
When using the [Truffle Framework](http://truffleframework.com/) to import a solidity contract, a "File not found" error is produced in the editor.

## Apparent Cause:
This appears to be due to the fact that the root directory for the import statement in truffle is *"/node_modules"* (relative to the *"contracts"* folder, the path becomes *"../node_modules"*). However, the problem does not go away when *"../node_modules/"* is appended to the front of the path.

## Specific Example:
In [this truffle tutorial](http://truffleframework.com/tutorials/robust-smart-contracts-with-openzeppelin), importing Open Zeppelin. In *"contracts/TutorialToken.sol"*:
```solidity
pragma solidity 0.4.21;
import "zeppelin-solidity/contracts/token/ERC20/StandardToken.sol";
```
The error appears on the second line, and reads: 
> Source "zeppelin-solidity/contracts/token/ERC20/StandardToken.sol" not found: File not found.

## Possible solution:
Enable the linter to check the *"node_modules"* directory in the project root for imported files.

**Comment by mpetrunic** [comment]
@Latrasis This should be closed.
