### ISSUE TITLE
can we make this into a standalone linting module?

### ISSUE THREAD

**Issue by SilentCicero** [Latrasis/linter-solidity#3]
Any chance we can make this into a standard alone linting module for NPM packages to use? Similar to `es-lint`.

By the way, great work thus far. We should really talk and build this into a solidity linting standard.

 Any thoughts on this? @Latrasis

**Comment by Latrasis** [comment]
@SilentCicero 

Sorry for the delay! I'm not sure what you mean exactly. I use the `solc` to simply output the errors, do I understand correctly that you want add more errors then just what `solc` outputs?

**Comment by travs** [comment]
@SilentCicero I think [solium](https://github.com/duaraghav8/Solium) fits the bill for your description.
