### ISSUE TITLE
Saving a file takes too long

### ISSUE THREAD

**Issue by kyroy** [Latrasis/linter-solidity#4]
When editing a file and saving the changes, it takes ~10 seconds to finish. Meanwhile the atom freezes.

I am working on this contract: https://github.com/ise-ethereum/on-chain-chess/blob/develop/contract/Chess.sol

**Comment by Latrasis** [comment]
@Kyroy:

This is mainly how nodejs works, since it's singlethreaded and how `solcjs` is blocking which `linter-solidity` depends on. I'll see if I can setup a child process.

**Comment by Latrasis** [comment]
Added a non-blocking child-process at: https://github.com/Latrasis/linter-solidity/commit/a955e5df487e81add0e444224960f04e6c1e76f6, `v0.4.0`

**Comment by lewisbarber** [comment]
Strange, this is still happening for me, only installed today... Node v8.1.2, Solidity v0.4.13...

Any ideas?

EDIT: Ah never mind, Atom doesn't block, but it still takes ~10s for the linter to update? Is this the expected behaviour?
